version: '3'
services:
  textapi:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "8080:8080"

  texttests:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.test